### ISSUE TITLE
dependencies on version of  radio confuse embedded-hal-compat

### ISSUE THREAD

**Issue by pdgilbert** [rust-iot/rust-radio-sx127x#38]
(Mentioned in #34, but unclear about details.) `rust-radio-sx127x`  dependencies on the version of  `radio` confuse `embedded-hal-compat`

Version 0.10.1 of `radio-sx127x` on crates.io uses `radio` "0.4.0" . This does not work with `embedded-hal-compat`. The builds fail with wrong number of arguments, with or without

```
[patch.crates-io]
radio = { git = "https://github.com/ryankurte/rust-radio.git", branch = "master" }
```
Version 0.10.1 of `radio-sx127x` on https://github.com/rust-iot/rust-radio-sx127x uses `radio` "0.7.0"  and my fork with the PR adding examples uses  `radio` "0.8.1" . A crate using these needs to use the same version:

```
radio-sx127x  = {  git = "https://github.com/rust-iot/rust-radio-sx127x", default-features = false }
radio         = { version = "0.7.0" }
```
or

```
radio-sx127x  = {  git = "https://github.com/pdgilbert/rust-radio-sx127x", default-features = false }
radio         = { version = "0.8.1" }
```
The patch above has no affect on build for either (but I have not tested running). Is it possible the patch is no longer needed for anything?

Some consolidation would be good.

**Comment by Cightline** [comment]
Oh my god thank you. I've been using your examples and I had `radio` set to `0.8.1` instead of `0.7.0` so compilation kept failing because the `radio::Transmit` trait wasn't implemented.

**Comment by pdgilbert** [comment]
Yes, the version interactions are messy. Something to look forward to when everything stabilizes a bit. I've looked briefly at `radio 0.9.0` but without success. Hoping @ryankurte will comment when there is a new set of pieces that should work together.

**Comment by ryankurte** [comment]
ahh, yeah i left a `patch` in there which made everything more tricky than it needed to be, sorry!

removed the patch and release `0.11.0` now uses `radio@0.9.0`, hopefully this is more straightforward.
@pdgilbert you may like to rebase your PR against this (there shouldn't be any _major_ changes i hope)

**Comment by Cightline** [comment]
> ahh, yeah i left a `patch` in there which made everything more tricky than it needed to be, sorry!

It's all good. The library code seems to be written well, I had my 2 feather boards blinking at each other earlier which was neat.

**Comment by pdgilbert** [comment]
Ok, in a small test it builds with
```
embedded-hal-compat = "0.1.3" 
radio-sx127x  = { version = "0.11.0", default-features = false }
radio         = { version = "0.9.0" }
```

and no patch. I'll try updating my PR.

**Comment by pdgilbert** [comment]
@Cightline, what MCU do your feather boards have and which device HAL are you using? And does it have an RFM95 radio?

**Comment by ryankurte** [comment]
> It's all good. The library code seems to be written well, I had my 2 feather boards blinking at each other earlier which was neat.

there's something about things blinking _over an RF link_ right?! glad it's mostly working for y'all.

**Comment by Cightline** [comment]
> @Cightline, what MCU do your feather boards have and which device HAL are you using? And does it have an RFM95 radio?

I have 2x of [these](https://www.adafruit.com/product/3178). I'm using the [feather_m0](https://crates.io/crates/feather_m0) crate.

**Comment by ryankurte** [comment]
> Hey I noticed you're subscribed to the rctestflight channel on YouTube. The whole reason why I bought these boards is so I can have reliable RC telemetry

oh neat! way back i used to build / fly weird thrust-vectoring quadrotors, telemetry was always a bit of a trick huh.

**Comment by Cightline** [comment]
Yep. The following is getting off topic so let me know if I need to post this somewhere else. 

I have a rough-draft on [Gitlab](https://gitlab.com/Sightline_/lora_mavlink/-/blob/master/src/main.rs#L493) if you wanna see what I have so far. The code runs off interrupts. After starting up both of the Feather M0 LoRa boards will oscillate between sending a beacon and listening for a beacon. Once the beacon is received they immediately start "talking" as fast as possible (which I am visualizing with the on-board LEDs). These boards have amazing range for their size.

**Comment by pdgilbert** [comment]
After figuring out I now need `use embedded_hal_compat::ForwardCompat` rather than `IntoCompat` and
append `.forward` rather than `.compat` I have my code working again now using 
```
embedded-hal = { version = "1.0.0-alpha.5" }  
old-e-h      = { version = "0.2.6", package = "embedded-hal" }
embedded-hal-compat = "0.4.0" 
radio         = { version = "0.9.1" }
driver-pal   = { git = "https://github.com/ryankurte/rust-driver-pal/", default-features = false } # 0.8.0-alpha5
...
```
I am a bit puzzled that I had to change `.try_delay_ms` back to `.delay_ms` so I tried briefly with `ReverseCompat` and `.reverse()` but that seemed to make things worse. I don't understand the contexts when one should consider `ReverseCompat` or `ForwardCompat`.

**Comment by pdgilbert** [comment]
I'm having trouble again with getting the proper mix of versions for `radio`, `rust-radio-sx127x`, and `embedded-hal-compat`.  I think the problem is the version mix, but the errors I'm getting are like

```
`error[E0432]: unresolved import `embedded_hal::delay::blocking::DelayMs`
 --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/driver-pal-0.8.0-alpha.5/src/wrapper.rs:5:37
  |
5 | use embedded_hal::delay::blocking::{DelayMs, DelayUs};
  |                                     ^^^^^^^
  |                                     |
  |                                     no `DelayMs` in `delay::blocking`
  |                                     help: a similar name exists in the module: `DelayUs`

error[E0405]: cannot find trait `DelayMs` in module `embedded_hal::delay::blocking`
  --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/driver-pal-0.8.0-alpha.5/src/lib.rs:59:38
   |
59 |     + embedded_hal::delay::blocking::DelayMs<u32>
   |                                      ^^^^^^^ help: a trait with a similar name exists: `DelayUs`
   |
  ::: /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/embedded-hal-1.0.0-alpha.6/src/delay.rs:14:5
   |
14 |     pub trait DelayUs {
   |     ----------------- similarly named trait `DelayUs` defined here

error[E0405]: cannot find trait `DelayMs` in module `embedded_hal::delay::blocking`
...
```

**Comment by Cightline** [comment]
I was messing around with this the other day. The following builds successfully on my system. `radio-sx127x` is the latest. 

```toml
[dependencies]
cortex-m            = "0.7.3"
feather_m0          = { version = "0.10.1", features = ["default", "rtic", "rt", "unproven", "rfm", "dma"] }
panic-halt          = "0.2.0"
heapless            = { verison = "0.7.7", features = ["default"], version = "0.7.7" }
panic-semihosting   = "0.5.6"
cortex-m-rtic       = { version = "0.6.0-rc.2", features = [] }
embedded-hal        = { version = "1.0.0-alpha.5" }
old-e-h             = { version = "0.2.6", package = "embedded-hal" }
radio               = { version = "0.9.1" }
driver-pal          = { version = "0.8.0-alpha.5", default_features = false }
radio-sx127x        = { path = "../../rust-radio-sx127x", default-features = false }
shared-bus-rtic     = { version = "0.2.2", features = ["thumbv6"] }
embedded-hal-compat = "0.4.0"
```
